name: Read Excel data

on:
  workflow_dispatch:
    inputs:
      excel_path:
        description: 'Path to Excel file'
        required: true

jobs:
  read_excel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install openpyxl
        run: pip install openpyxl

      - name: Read Excel data
        run: python read_excel.py ${{ github.event.inputs.excel_path }}
