name: CI

on:
  workflow_dispatch:
    inputs:
      excel_file:
        description: Path to Excel file
        required: true
   
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  read-excel-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get install python3-pip
          pip3 install pandas
      
      - name: Read Excel data
        run: |
          input_file=${{ github.event.inputs.excel_file }}
          python3 read_excel.py $input_file
      
      - name: Do something with the data
        run: |
          # Use the data in your workflow as needed
          # For example, pass it as an argument to a command
          
      - name: Read input data
        run: |
         input_data_path=${{ github.event.client_payload.input_data }}
         python read_data.py $input_data_path
          # Access the input data [input data is path to excel file]
