name: read-excel

on:
  workflow_dispatch:
    inputs:
      excel_file_path:
        description: 'Path to Excel file'
        required: true

jobs:
  read_excel:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install openpyxl
    - name: Read Excel file
      run: python read_excel.py ${{ secrets.EXCEL_FILE_PATH }}
      env:
        EXCEL_FILE_PATH: ${{ secrets.EXCEL_FILE_PATH }}
